In [1]:
#import numpy as np 

In [2]:
import numpy as np 

Creating Arrays

np.array([])
np.arrange()
np.zeroes()
np.ones()
np.random.rand()
np.random.randint()
np.random.randn()

In [3]:
a = np.array([])

In [4]:
print(a)

[]


In [6]:
a #in array only type of data is present 

array([], dtype=float64)

In [7]:
len(a)

0

sum()

In [8]:
sum(a)

0

In [10]:
a.shape #shows the shape of arrow

(0,)

In [11]:
a.size

0

In [12]:
a.dtype # datatype #DETECTING THE DATA TYPE

dtype('float64')

In [13]:
a.astype('int8')  #integer of 8 bit  IT JUST COPY AND CHANGES THE DATA TYPE 

array([], dtype=int8)

In [14]:
a.tolist()

[]

In [15]:
type(a)

numpy.ndarray

In [16]:
type(a.tolist())

list

In [17]:
b = np.array([3,4,5,6,7,8])

In [18]:
b

array([3, 4, 5, 6, 7, 8])

In [19]:
b.shape

(6,)

In [20]:
b.size

6

In [22]:
b.dtype

dtype('int32')

#data operation 

In [25]:
#Accesing data 
# arr(indexing)(bslicing is available here)
# subscripting arr [row,col,3rth, 4th]

In [26]:
b[3]

6

In [27]:
b[:3]

array([3, 4, 5])

In [28]:
#the first element is row , then columns 


In [30]:
c = np.array([[4,5,6,7],[9,3,76,2],[56,76,3,8]])

In [32]:
c


array([[ 4,  5,  6,  7],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])

In [33]:
c.shape

(3, 4)

In [35]:
c.size


12

In [36]:
b[3]

6

In [37]:
b

array([3, 4, 5, 6, 7, 8])

In [38]:
b[3] = 16

In [39]:
c[:2,1:]

array([[ 5,  6,  7],
       [ 3, 76,  2]])

In [40]:
b*3

array([ 9, 12, 15, 48, 21, 24])

In [41]:
c+10

array([[14, 15, 16, 17],
       [19, 13, 86, 12],
       [66, 86, 13, 18]])

In [42]:
c.reshape(2,6)

array([[ 4,  5,  6,  7,  9,  3],
       [76,  2, 56, 76,  3,  8]])

In [43]:
c

array([[ 4,  5,  6,  7],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])

In [44]:
c.reshape(3,4)

array([[ 4,  5,  6,  7],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])

In [45]:
c.T #Transpose 

array([[ 4,  9, 56],
       [ 5,  3, 76],
       [ 6, 76,  3],
       [ 7,  2,  8]])

In [46]:
c.min()

2

In [47]:
c.max()

76

In [48]:
c.sum()

255

In [49]:
c


array([[ 4,  5,  6,  7],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])

In [50]:
c[4,0:4]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [52]:
np.append(c,[[9,99,999,199]],axis =0) #

array([[  4,   5,   6,   7],
       [  9,   3,  76,   2],
       [ 56,  76,   3,   8],
       [  9,  99, 999, 199]])

In [53]:
c.sum()

255

In [54]:
c


array([[ 4,  5,  6,  7],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])

In [55]:
# it is just returning , not original one is changing 


In [56]:
d = np.append(c,[[9,99,999,199]],axis =0)

In [57]:
d

array([[  4,   5,   6,   7],
       [  9,   3,  76,   2],
       [ 56,  76,   3,   8],
       [  9,  99, 999, 199]])

In [58]:
np.append(d,[[11],[411],[99],[999]])

array([  4,   5,   6,   7,   9,   3,  76,   2,  56,  76,   3,   8,   9,
        99, 999, 199,  11, 411,  99, 999])

In [59]:
np.append(d,[[11],[411],[99],[999]],axis = 1)

array([[  4,   5,   6,   7,  11],
       [  9,   3,  76,   2, 411],
       [ 56,  76,   3,   8,  99],
       [  9,  99, 999, 199, 999]])

In [64]:
np.insert(d,3,5,axis = 1)   #shift+tab shows help #tab shows option 


array([[  4,   5,   6,   5,   7],
       [  9,   3,  76,   5,   2],
       [ 56,  76,   3,   5,   8],
       [  9,  99, 999,   5, 199]])

a.sum
a.max
a.min
a.argmax 
a.argmin
a.mean
a.var
a.std
a.sort


In [65]:
c.sum(axis = 1)

array([ 22,  90, 143])

In [67]:
c.sum(axis = 0)


array([69, 84, 85, 17])

In [68]:
c


array([[ 4,  5,  6,  7],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])