In [2]:
import pandas as pd

In [4]:
import warnings 
warnings.filterwarnings('ignore')

# Data types in pandas 
1.series(1-D/single col)*
2.DataFrame(2D/Tabular Data)*
3.Panel (3D /MultiTable Data)

# Creating Data

In [5]:
s = pd.Series([])

In [6]:
s

Series([], dtype: float64)

In [7]:
print(s)

Series([], dtype: float64)


In [8]:
type(s)

pandas.core.series.Series

In [9]:
s.dtype

dtype('float64')

In [10]:
s.shape

(0,)

In [11]:
s.size

0

In [12]:
s.head()

Series([], dtype: float64)

In [13]:
s.tail()

Series([], dtype: float64)

In [14]:
s.sample(0)

Series([], dtype: float64)

In [15]:
s1 = pd.Series([3,4,5,6,7,8,9,0,9,8,7,6,6,5,4,3,2,3,4,56,7,88,77,66,55,44,556]
        )

In [17]:
s1  #showing index as well as values 

0       3
1       4
2       5
3       6
4       7
5       8
6       9
7       0
8       9
9       8
10      7
11      6
12      6
13      5
14      4
15      3
16      2
17      3
18      4
19     56
20      7
21     88
22     77
23     66
24     55
25     44
26    556
dtype: int64

In [19]:
s1.shape

(27,)

s1.size

In [21]:
s1.size

27

In [22]:
s1.head()

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [23]:
s1.tail()

22     77
23     66
24     55
25     44
26    556
dtype: int64

In [24]:
s1.head(6)

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64

In [25]:
s1.sample(5) #showing 5 random values

14     4
22    77
21    88
2      5
7      0
dtype: int64

In [27]:
s1.value_counts() #counts the no of times a value occured

7      3
6      3
4      3
3      3
9      2
8      2
5      2
66     1
56     1
55     1
556    1
88     1
77     1
44     1
2      1
0      1
dtype: int64

In [28]:
s1.unique()

array([  3,   4,   5,   6,   7,   8,   9,   0,   2,  56,  88,  77,  66,
        55,  44, 556], dtype=int64)

In [29]:
s1.nunique()

16

In [30]:
len(s1.unique())

16

In [32]:
s1.values #comverted into numpy array

array([  3,   4,   5,   6,   7,   8,   9,   0,   9,   8,   7,   6,   6,
         5,   4,   3,   2,   3,   4,  56,   7,  88,  77,  66,  55,  44,
       556], dtype=int64)

In [34]:
s1.values.tolist() #converted  to list 

[3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 9,
 8,
 7,
 6,
 6,
 5,
 4,
 3,
 2,
 3,
 4,
 56,
 7,
 88,
 77,
 66,
 55,
 44,
 556]

In [35]:
s2 = pd.Series({'a':30,'b':10,'c':10})

In [36]:
s2 #yahan index ke badle abc bangya ye ajeeb hai -dict aise frame ho taha 

a    30
b    10
c    10
dtype: int64

In [40]:
s3 = pd.Series({'a':[5,6],'b':[9,99],'c':[0,9]})

In [41]:
s3

a     [5, 6]
b    [9, 99]
c     [0, 9]
dtype: object

In [46]:
#dict me key into index or hum wo dal sakte hai
s4 = pd.Series([4,7,8,7,3,9],index = list('xyzpqr'),name = "Data")
s4

x    4
y    7
z    8
p    7
q    3
r    9
Name: Data, dtype: int64

In [45]:
list('xyzpqr')

['x', 'y', 'z', 'p', 'q', 'r']

In [47]:
s4.max()

9

In [49]:
s4.idxmax()

'r'

### Accesing /Mmodfying Series values 

In [50]:
s1

0       3
1       4
2       5
3       6
4       7
5       8
6       9
7       0
8       9
9       8
10      7
11      6
12      6
13      5
14      4
15      3
16      2
17      3
18      4
19     56
20      7
21     88
22     77
23     66
24     55
25     44
26    556
dtype: int64

In [51]:
s1[5]

8

In [53]:
s1[5] = 77 #mutable

In [54]:
del s1[6]

In [55]:
s1.head(6)

0     3
1     4
2     5
3     6
4     7
5    77
dtype: int64

In [56]:
s1.head(10) #6 number wala gum hogya

0      3
1      4
2      5
3      6
4      7
5     77
7      0
8      9
9      8
10     7
dtype: int64

In [57]:
s2

a    30
b    10
c    10
dtype: int64

In [58]:
s2['a']

30

In [59]:
s2[0]

30

In [60]:
s2['b']

10

In [63]:
s2[2]

10

In [64]:
#agar me index me shuffled values dal diye na to wo phir indexing uske mutabik hoga 

In [65]:
s2['d'] = 99

In [66]:
s2

a    30
b    10
c    10
d    99
dtype: int64

# Creating DataFrame

In [68]:
d = pd.DataFrame()

In [69]:
d

Empty DataFrame
Columns: []
Index: []

In [70]:
type(d)

pandas.core.frame.DataFrame

In [71]:
print(d)

Empty DataFrame
Columns: []
Index: []


In [73]:
d.size

0

In [74]:
d.shape

(0, 0)

In [75]:
d.head()

Empty DataFrame
Columns: []
Index: []

In [76]:
d.tail()

Empty DataFrame
Columns: []
Index: []

In [77]:
d.sample(0)

Empty DataFrame
Columns: []
Index: []

In [78]:
df = pd.DataFrame([3,4,5,8,9,4,6,8]) #dikhne me acha lag raha hai 
df  #row no or column no banaya

0
0  3
1  4
2  5
3  8
4  9
5  4
6  6
7  8

In [79]:
df1 = pd.DataFrame({'a':[20,'hari'],'b':["harry",'jerry']})

In [80]:
df1

a      b
0    20  harry
1  hari  jerry

In [81]:
#wahhh yahan to mast hai apne aap hi column banadiya 

## sabse jyadda yahi kam aayega

In [82]:
df1 = pd.DataFrame({'a':[20,'hari'],'b':["harry"]})

ValueError: arrays must all be same length

In [83]:
#kyu hua aisa list me dal
df1 = pd.DataFrame({'a':[20],'b':["harry"]})

In [84]:
pd.DataFrame({'a':[20],'b':["harry"]})

a      b
0  20  harry

In [86]:
d2 = pd.DataFrame([[2,'harry0'],[9,"harry"],[25,'hi']],columns = ['age','Name'],index = ['x','y','z'])
d2

age    Name
x    2  harry0
y    9   harry
z   25      hi

### Accesing /Modifying / DataFrame

In [90]:
d2['age'] #series jesa dikh raha hai 

x     2
y     9
z    25
Name: age, dtype: int64

In [92]:
d2['Name']

x    harry0
y     harry
z        hi
Name: Name, dtype: object

In [93]:
d2['x']  #wrong

KeyError: 'x'

In [94]:
d2(0)

TypeError: 'DataFrame' object is not callable

In [97]:
d2.loc['x']  #ye bhi series jesa dikh raha hai agar row chaiye to loc lagao 

age          2
Name    harry0
Name: x, dtype: object

In [99]:
d2.T #.loc me transpose kardeta hai wo 


x      y   z
age        2      9  25
Name  harry0  harry  hi

In [103]:
print(d2.loc)
d2.loc

In [104]:
#puri series me change karni 

In [105]:
d2


age    Name
x    2  harry0
y    9   harry
z   25      hi

In [106]:
d2['age']['x'] = 22

In [107]:
d2

age    Name
x   22  harry0
y    9   harry
z   25      hi

In [112]:
d2['Extra']  = pd.Series([True,False,True],index = list('xyz'))

In [113]:
d2

age    Name  Extra
x   22  harry0   True
y    9   harry  False
z   25      hi   True

In [114]:
#Nan = not a number == matlab data nhi hai as a number

In [111]:
#empty ko represent karne ke Nan use kiya gya 

In [116]:
d2['Extra']  = pd.Series([True,False,True],index = list('yzp'))

In [118]:
d2 #fitin karna 

age    Name  Extra
x   22  harry0    NaN
y    9   harry   True
z   25      hi  False

#### abhi hum modify hi kar rahe hai

In [119]:
del d2['Extra']

In [120]:
d2

age    Name
x   22  harry0
y    9   harry
z   25      hi

In [122]:
d2['Extra']  = pd.Series([True,False,True,False],index = list('xyzp'))

In [123]:
d2

age    Name  Extra
x   22  harry0   True
y    9   harry  False
z   25      hi   True

In [125]:
d2[['age','Extra']]

age  Extra
x   22   True
y    9  False
z   25   True

In [126]:
d2[['age']]

age
x   22
y    9
z   25

In [127]:
d2.index

Index(['x', 'y', 'z'], dtype='object')

In [128]:
d2.columns

Index(['age', 'Name', 'Extra'], dtype='object')

In [129]:
d2.values

array([[22, 'harry0', True],
       [9, 'harry', False],
       [25, 'hi', True]], dtype=object)

In [130]:
d2.values.tolist()

[[22, 'harry0', True], [9, 'harry', False], [25, 'hi', True]]

### Operations 
1.Creating 
2.Accessing / Modifying 
3.Statistical Functions 
4. String Functions 
5. Iteration 
6. Sorting 
7.Data Aggregations/Groupby 
8.Missing Data / its Treatment 
9. Merging/Joining /Concatenation 
10.File Handling 
11.Date Time Functionality 
12.Graphical Visualisation 

### File handling

In [132]:
# source data ka -- kaggle.com 


In [133]:
pd.read_clipboard()

#    A
0  1  459
1  2  100
2  3  130

In [ ]:
#for reading data 
pd.read_clipboard
pd.read_csv
pd.read_excel 
pd.read_json 
pd.read_html 
pd.read_pickle
pd.read_feather
pd.read_hdf