# write pip install pandas seaborn 

In [5]:
import numpy as np 

## Creating arrays 

1. np.array([])
2.np.arrange([])
3.np.ones()
4.np.zeroes()
5.np.linspace()
6.np.random.randit()
7.np.random.randit()
8.np.radnom.randit()

In [6]:
#all this functions gives us numpy array 
a = np.array([])
#list hi banani hai , par usey array me pass kardiya 
#to kya bana array -array is homogenous data


In [7]:
print(a)

[]


In [8]:
a 

array([], dtype=float64)

##### data type usi ka ata hai jisme ek hi type ki values aati hai 


In [10]:
len(a)

0

In [12]:
sum(a) # adds all of a 


0

In [13]:
a.shape #shows the dimension and value

(0,)

In [15]:
a.size #no.of elements 

0

In [21]:
a.dtype #datatype--finding the data type 

dtype('float64')

In [19]:
a.astype('int8') #it's not converted just returned -- that is a is same 

array([], dtype=int8)

In [20]:
a.dtype 

dtype('float64')

In [23]:
#Typecasting 
a.tolist()  #it has become list 

[]

In [24]:
type(a)

numpy.ndarray

In [26]:
type(a.tolist())

list

In [27]:
b = np.array([3,4,5,6,7,8])
b

array([3, 4, 5, 6, 7, 8])

In [28]:
b.shape

(6,)

In [29]:
b.size

6

In [30]:
b.dtype 

dtype('int32')

## data operation  -  modify 

# 1.Accessing Data 
#Indexing ->  arr[ind]
#Subscripting -> arr[subscripting] = arr [row,col,3rd,4th,...nd]


In [31]:
b[3]

6

In [33]:
#subscripting 
#[4,8,6] - 1D 
#[4,6,7]
#[5,5,6] -- 2D 
#[4,5,6,7]
#[1,2,3,4] - 3D (array/matrix)
#shape should be (3,4)
# size (12)- no of elements 
#first row -- description is defining dimensions 


In [34]:
b[3]

6

In [35]:
b[:3]

array([3, 4, 5])

In [36]:
b

array([3, 4, 5, 6, 7, 8])

In [43]:
b[2:4:2]

array([5])

In [44]:
c = np.array([[4,5,6,7],[9,3,76,2],[56,76,3,8]])
c

array([[ 4,  5,  6,  7],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])

In [45]:
c.shape

(3, 4)

In [47]:
c.size

12

In [41]:
#first dimension [[1st row][2nd row][3rd row]]- 3 rows 
# numbering starts from 0 , columns - [col1,col2,col3][col1,col2,col3]...
# what is meaning of subsripting only 2 things need to be written - [row,col]- just this much for subscripting 
#a[1,1]-indicates row 1 column 1 
#slicing is for continuous portion -- for image processing -- []

In [48]:
b[3]

6

In [49]:
b[:3]

array([3, 4, 5])

In [50]:
c[:2,1:]

array([[ 5,  6,  7],
       [ 3, 76,  2]])

In [51]:
b[3] = 16 
b

array([ 3,  4,  5, 16,  7,  8])

In [52]:
b*3
print(b)
print(b*3)

[ 3  4  5 16  7  8]
[ 9 12 15 48 21 24]


In [53]:
c+10

array([[14, 15, 16, 17],
       [19, 13, 86, 12],
       [66, 86, 13, 18]])

In [55]:
print(c.reshape(2,6))
print(c)

[[ 4  5  6  7  9  3]
 [76  2 56 76  3  8]]
[[ 4  5  6  7]
 [ 9  3 76  2]
 [56 76  3  8]]


In [57]:
print(c.reshape(1,8))

ValueError: cannot reshape array of size 12 into shape (1,8)

In [58]:
c.T # transposing 

array([[ 4,  9, 56],
       [ 5,  3, 76],
       [ 6, 76,  3],
       [ 7,  2,  8]])

#### statistical functions

In [60]:
c.sum()

255

In [62]:
c[4,:] = [9,99,99,199]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [63]:
np.append(c,[9,99,99,999])  #it's numpy one 

array([  4,   5,   6,   7,   9,   3,  76,   2,  56,  76,   3,   8,   9,
        99,  99, 999])

In [71]:
 d = np.append(c,[[9,99,999,199]],axis = 0 ) #axis - 0 for row 

In [72]:
d

array([[  4,   5,   6,   7],
       [  9,   3,  76,   2],
       [ 56,  76,   3,   8],
       [  9,  99, 999, 199]])

In [73]:
e = np.append(d,[[9],[99],[999],[199]],axis = 1) #axis= 1 is for column

In [74]:
e

array([[  4,   5,   6,   7,   9],
       [  9,   3,  76,   2,  99],
       [ 56,  76,   3,   8, 999],
       [  9,  99, 999, 199, 199]])

In [76]:
f = np.append(e,[[0],[1],[2],[3]],axis = 1)

In [77]:
f

array([[  4,   5,   6,   7,   9,   0],
       [  9,   3,  76,   2,  99,   1],
       [ 56,  76,   3,   8, 999,   2],
       [  9,  99, 999, 199, 199,   3]])

In [79]:
#look for isertion #help is found - shift+tab 

a.sum
a.min
a.max 
a.argmin 
a.argmin 
a.mode
a.cusum 
a.var
a.std 
a.sort 


### mathematics 

a.prod 
a.cumsum
a.dot 
#c.sum(axis = 0)
#c.sum(axis = 1)
a.round 
a+4
a/4

## day_11

In [81]:
np.arange(1,20,3)  #create array the way it was in range

array([ 1,  4,  7, 10, 13, 16, 19])

In [82]:
np.linspace(1,20,10)  #here we decides the number of values 

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [83]:
np.zeros((3,4)) #only 0's give dimensions 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.ones((4,3))*255   #for all ones 

array([[255., 255., 255.],
       [255., 255., 255.],
       [255., 255., 255.],
       [255., 255., 255.]])

In [85]:
np.random.random((2,6))  #i am making a random array 

array([[0.33492421, 0.36705382, 0.13307931, 0.40095346, 0.63933295,
        0.15557383],
       [0.89624815, 0.68803876, 0.01516251, 0.81848983, 0.23659342,
        0.00643687]])

In [86]:
np.random.random((3,4)) #0.0-0.5

array([[0.80046689, 0.92104008, 0.95962683, 0.9379604 ],
       [0.35240424, 0.4136136 , 0.0395482 , 0.65606549],
       [0.76147467, 0.87065366, 0.39132765, 0.97810011]])

In [87]:
np.random.random((3,4))*8

array([[3.69941365, 3.5803362 , 7.69598339, 7.37110535],
       [2.45782596, 2.50020553, 2.37509262, 5.92716904],
       [6.13795294, 6.79396673, 5.12652263, 5.19392534]])

In [88]:
np.random.randint(10,1000,(3,4)) #values between 10,1000

array([[805, 322,  52, 759],
       [790, 593, 648, 937],
       [101, 669, 570, 189]])

In [90]:
np.random.randn(3,4)  #it behaves sinc function

array([[ 1.21002233,  0.03007301,  0.39879644, -2.00371549],
       [ 1.5435528 ,  1.27333743,  0.01844394, -0.17411215],
       [ 2.20889575, -1.57112195, -0.49433127,  1.67615622]])

## File Handling

In [91]:
k = np.random.randint(10,1000,(3,4))
k

array([[459, 594, 801, 864],
       [100,  11, 464, 208],
       [130, 286, 760, 130]])

In [92]:
np.save('myfile',k) #file name or array 

In [94]:
m = np.load('myfile.npy')
m

array([[459, 594, 801, 864],
       [100,  11, 464, 208],
       [130, 286, 760, 130]])

In [108]:
import os 
os.getcwd()  #os module me present directory , change directory , ye sab dekh sakte hai 

'F:\\15th_june_AI_batch\\day_10'

## os.chdir('') can keep here the address 

In [101]:
np.savetxt('onefile.txt',k,fmt = '%d',delimiter = ',')

In [103]:
np.savetxt('onefile.csv',k,fmt = '%d',delimiter = ',',header = 'A,B,C,D',comments = '')

In [107]:
p = np.loadtxt('onefile.csv',dtype = str,delimiter = ',')
p

array([['A', 'B', 'C', 'D'],
       ['459', '594', '801', '864'],
       ['100', '11', '464', '208'],
       ['130', '286', '760', '130']], dtype='<U3')