# NumPy Exercises - Solutions

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [9]:
np.zeros((1,1,10))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

#### Create an array of 10 ones

In [10]:
np.ones((1,1,10))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

#### Create an array of 10 fives

In [20]:
d = np.ones((1,1,10))*5  
d


array([[[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]]])

#### Create an array of the integers from 10 to 50

In [22]:
np.array(range(10,51,1))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [23]:
np.array(range(10,51,2))

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [25]:
np.arange(10,51,2) #same thing is done using arange func

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [28]:
np.array([[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
#or it can be done using this identity function
np.identity(3,)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
#the same can be done to get a int value 
np.identity(3,int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Use NumPy to generate a random number between 0 and 1

In [33]:
np.random.rand(1)

array([0.82271333])

In [42]:
#or 
np.random.randint(0,1,(1,1))

array([[0]])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [43]:
np.random.rand(5,5)

array([[0.18224439, 0.62517997, 0.63275954, 0.67029135, 0.42957349],
       [0.04494384, 0.95474715, 0.39622149, 0.278658  , 0.53568347],
       [0.87963788, 0.36874779, 0.88110663, 0.31029057, 0.67037069],
       [0.08896199, 0.77387523, 0.03572722, 0.32274967, 0.15309362],
       [0.0167111 , 0.55976059, 0.94121007, 0.25604955, 0.21330563]])

In [44]:
np.random.randn(5,5)

array([[-3.03047863, -0.48185412,  0.59684413, -1.60879619,  0.52626029],
       [-0.95681923, -1.29228647,  0.5721909 , -1.60544011,  0.50105522],
       [-0.13936075,  0.58901391, -0.24864632, -0.66848119, -1.08311618],
       [-1.21113741, -1.45524339,  0.37330672,  0.28354208, -0.5585251 ],
       [ 0.73276822, -0.90527069, -1.59484201, -1.01642479, -1.71643574]])

In [46]:
np.random.random_sample((5,5))

array([[0.95387175, 0.76796762, 0.56891039, 0.33286426, 0.198801  ],
       [0.49496216, 0.70808765, 0.27497036, 0.10125572, 0.69208176],
       [0.8856377 , 0.68095299, 0.04871778, 0.21622727, 0.7996802 ],
       [0.48070347, 0.06494579, 0.45171987, 0.13706646, 0.47545093],
       [0.91184975, 0.4025834 , 0.83091769, 0.34318126, 0.50290132]])

#### Create the following matrix:

In [55]:
d = np.arange(0.01,1.01,0.01,float)

In [56]:
d.reshape((10,10))

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [72]:
np.linspace(0.01,1.00,100).reshape((10,10))

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [65]:
np.arange(0,1.05263158,0.05263158)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.2631579 , 0.31578948, 0.36842106, 0.42105264, 0.47368422,
       0.5263158 , 0.57894738, 0.63157896, 0.68421054, 0.73684212,
       0.7894737 , 0.84210528, 0.89473686, 0.94736844, 1.00000002])

In [73]:
#or
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [81]:
a = np.linspace(1,25,25,dtype = int)
b = a.reshape(5,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [82]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [85]:
b[3,4]

20

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [86]:
b[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [87]:
b[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [88]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [91]:
b[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [92]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [96]:
b[4:,0:]

array([[21, 22, 23, 24, 25]])

In [95]:
#this is the output  ;;   ----array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [97]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [98]:
b[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

In [99]:
b.sum()

325

In [100]:
b.std()

7.211102550927978

#### Get the standard deviation of the values in mat

7.2111025509279782

In [101]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [104]:
b.sum(axis = 0)

array([55, 60, 65, 70, 75])

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

# Great Job!